// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: presence/v1/presence.proto

// The contract between the API nodes and the presence service.
//
// This file is the boundary. Until Stage 6 the API node read the Redis sorted
// set itself, so "the presence API" was a Go method and the compiler checked
// every caller. Now the caller and the callee are two processes that are
// deployed separately, and this file is the only thing they agree on.
//
// The version is in the package name — presence.v1 — because that is what a
// breaking change costs once there are two processes. A field cannot simply be
// renamed any more: during a rolling deploy the old API nodes and the new
// service run at the same time, so both sides have to understand both shapes.
// A v2 package is how that is done when a change cannot be made compatible.

package presencepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PresenceService_Heartbeat_FullMethodName = "/presence.v1.PresenceService/Heartbeat"
	PresenceService_Online_FullMethodName    = "/presence.v1.PresenceService/Online"
)

// PresenceServiceClient is the client API for PresenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PresenceService answers "who has a socket open right now?".
//
// Two calls, and they are opposites: nodes write with Heartbeat and read with
// Online. Both are unary. Streaming was considered for Heartbeat and rejected:
// a stream is a thing that can be half-open, and the one failure this service
// must survive is a node that dies without saying goodbye. A call that either
// happened or did not is easier to reason about than a stream that looks alive
// because nobody has written to it.
type PresenceServiceClient interface {
	// Heartbeat records that these users are online on this node, right now.
	//
	// It is a full replacement of what that node claims, not a delta, so a node
	// that missed a beat repairs itself with the next one. No goodbye call
	// exists on purpose — see HeartbeatRequest.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Online reports which of the given users are online anywhere.
	Online(ctx context.Context, in *OnlineRequest, opts ...grpc.CallOption) (*OnlineResponse, error)
}

type presenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceServiceClient(cc grpc.ClientConnInterface) PresenceServiceClient {
	return &presenceServiceClient{cc}
}

func (c *presenceServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, PresenceService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) Online(ctx context.Context, in *OnlineRequest, opts ...grpc.CallOption) (*OnlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineResponse)
	err := c.cc.Invoke(ctx, PresenceService_Online_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PresenceServiceServer is the server API for PresenceService service.
// All implementations must embed UnimplementedPresenceServiceServer
// for forward compatibility.
//
// PresenceService answers "who has a socket open right now?".
//
// Two calls, and they are opposites: nodes write with Heartbeat and read with
// Online. Both are unary. Streaming was considered for Heartbeat and rejected:
// a stream is a thing that can be half-open, and the one failure this service
// must survive is a node that dies without saying goodbye. A call that either
// happened or did not is easier to reason about than a stream that looks alive
// because nobody has written to it.
type PresenceServiceServer interface {
	// Heartbeat records that these users are online on this node, right now.
	//
	// It is a full replacement of what that node claims, not a delta, so a node
	// that missed a beat repairs itself with the next one. No goodbye call
	// exists on purpose — see HeartbeatRequest.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Online reports which of the given users are online anywhere.
	Online(context.Context, *OnlineRequest) (*OnlineResponse, error)
	mustEmbedUnimplementedPresenceServiceServer()
}

// UnimplementedPresenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPresenceServiceServer) Online(context.Context, *OnlineRequest) (*OnlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Online not implemented")
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}
func (UnimplementedPresenceServiceServer) testEmbeddedByValue()                         {}

// UnsafePresenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServiceServer will
// result in compilation errors.
type UnsafePresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

func RegisterPresenceServiceServer(s grpc.ServiceRegistrar, srv PresenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedPresenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PresenceService_ServiceDesc, srv)
}

func _PresenceService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_Online_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).Online(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_Online_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).Online(ctx, req.(*OnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PresenceService_ServiceDesc is the grpc.ServiceDesc for PresenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PresenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "presence.v1.PresenceService",
	HandlerType: (*PresenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _PresenceService_Heartbeat_Handler,
		},
		{
			MethodName: "Online",
			Handler:    _PresenceService_Online_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "presence/v1/presence.proto",
}
