// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: presence/v1/presence.proto

// The contract between the API nodes and the presence service.
//
// This file is the boundary. Until Stage 6 the API node read the Redis sorted
// set itself, so "the presence API" was a Go method and the compiler checked
// every caller. Now the caller and the callee are two processes that are
// deployed separately, and this file is the only thing they agree on.
//
// The version is in the package name — presence.v1 — because that is what a
// breaking change costs once there are two processes. A field cannot simply be
// renamed any more: during a rolling deploy the old API nodes and the new
// service run at the same time, so both sides have to understand both shapes.
// A v2 package is how that is done when a change cannot be made compatible.

package presencepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which node is speaking. It is part of the identity of an entry, so one
	// user on a phone and a laptop, on two different nodes, is two entries and
	// either one keeps them online.
	//
	// Without it, the node that lost the user would erase the node that still
	// has them.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Every user with a socket on this node. The whole list every time.
	//
	// There is no "user went offline" call, and that is the design, not a gap.
	// The one moment a node cannot send such a call is the moment it is killed,
	// which is exactly the case presence has to survive. Entries expire on
	// their own instead, so a node that stops beating takes its users with it.
	UserIds       []uint64 `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Empty. The reply carries no information beyond "this was written", and an
// empty message is still the right shape: a field can be added later without
// changing the method.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{1}
}

type OnlineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The users being asked about — usually the members of one room.
	UserIds       []uint64 `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineRequest) Reset() {
	*x = OnlineRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRequest) ProtoMessage() {}

func (x *OnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRequest.ProtoReflect.Descriptor instead.
func (*OnlineRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type OnlineResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only the online ones. The caller already knows the full list it asked
	// about, so sending a flag per user would put the same ids on the wire
	// twice.
	OnlineUserIds []uint64 `protobuf:"varint,1,rep,packed,name=online_user_ids,json=onlineUserIds,proto3" json:"online_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineResponse) Reset() {
	*x = OnlineResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineResponse) ProtoMessage() {}

func (x *OnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineResponse.ProtoReflect.Descriptor instead.
func (*OnlineResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{3}
}

func (x *OnlineResponse) GetOnlineUserIds() []uint64 {
	if x != nil {
		return x.OnlineUserIds
	}
	return nil
}

var File_presence_v1_presence_proto protoreflect.FileDescriptor

const file_presence_v1_presence_proto_rawDesc = "" +
	"\n" +
	"\x1apresence/v1/presence.proto\x12\vpresence.v1\"F\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x04R\auserIds\"\x13\n" +
	"\x11HeartbeatResponse\"*\n" +
	"\rOnlineRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x04R\auserIds\"8\n" +
	"\x0eOnlineResponse\x12&\n" +
	"\x0fonline_user_ids\x18\x01 \x03(\x04R\ronlineUserIds2\xa0\x01\n" +
	"\x0fPresenceService\x12J\n" +
	"\tHeartbeat\x12\x1d.presence.v1.HeartbeatRequest\x1a\x1e.presence.v1.HeartbeatResponse\x12A\n" +
	"\x06Online\x12\x1a.presence.v1.OnlineRequest\x1a\x1b.presence.v1.OnlineResponseB0Z.go-chat-backend/internal/presencepb;presencepbb\x06proto3"

var (
	file_presence_v1_presence_proto_rawDescOnce sync.Once
	file_presence_v1_presence_proto_rawDescData []byte
)

func file_presence_v1_presence_proto_rawDescGZIP() []byte {
	file_presence_v1_presence_proto_rawDescOnce.Do(func() {
		file_presence_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)))
	})
	return file_presence_v1_presence_proto_rawDescData
}

var file_presence_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_presence_v1_presence_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),  // 0: presence.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 1: presence.v1.HeartbeatResponse
	(*OnlineRequest)(nil),     // 2: presence.v1.OnlineRequest
	(*OnlineResponse)(nil),    // 3: presence.v1.OnlineResponse
}
var file_presence_v1_presence_proto_depIdxs = []int32{
	0, // 0: presence.v1.PresenceService.Heartbeat:input_type -> presence.v1.HeartbeatRequest
	2, // 1: presence.v1.PresenceService.Online:input_type -> presence.v1.OnlineRequest
	1, // 2: presence.v1.PresenceService.Heartbeat:output_type -> presence.v1.HeartbeatResponse
	3, // 3: presence.v1.PresenceService.Online:output_type -> presence.v1.OnlineResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_presence_v1_presence_proto_init() }
func file_presence_v1_presence_proto_init() {
	if File_presence_v1_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_v1_presence_proto_goTypes,
		DependencyIndexes: file_presence_v1_presence_proto_depIdxs,
		MessageInfos:      file_presence_v1_presence_proto_msgTypes,
	}.Build()
	File_presence_v1_presence_proto = out.File
	file_presence_v1_presence_proto_goTypes = nil
	file_presence_v1_presence_proto_depIdxs = nil
}
